### ISSUE TITLE
emqxConfig.EMQX_**  gives configmap errors and exit container

### ISSUE THREAD

**Issue by rjbaat** [emqx/emqx-rel#448]
Hi,

I have used the EMQX helm chart from version: v1.0.0-beta.3. 
This was working for me. But now i want to install a new cluster with the latest helm template version v.4.0.1. But this gives me all sorts of config map errors. This wasn't happening on the beta version. For example adding the answer: 

emqxConfig.EMQX_ALLOW_ANONYMOUS=false will result in this error:

```
failed to install app emqx. Error: release emqx failed: ConfigMap in version \"v1\" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects \" or n, but found f, error found in #10 byte of ...|ONYMOUS\":false,\"EMQX|..., bigger context ...|\"apiVersion\":\"v1\",\"data\":{\"EMQX_ALLOW_ANONYMOUS\":false,\"EMQX_CLUSTER__K8S__ADDRESS_TYPE\":\"hostname\",|...\n
```
But when adding it as string like emqxConfig.EMQX_ALLOW_ANONYMOUS="false" it is not picked up by EMQX and exits the containers.

Any idea what i can do to make it work again?

**Comment by rjbaat** [comment]
Does it has something to do with the new configmap.yaml?

The old one looks like: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emqx.fullname" . }}-env
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $index, $value := .Values.emqxConfig}}
    {{$index}}: "{{ $value }}" 
  {{- end}}
```

And the new one looks like: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emqx.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- toYaml .Values.emqxConfig | nindent 2 }}
```

This might help: https://stackoverflow.com/questions/56261546/helm-config-map-with-yaml-file
