### ISSUE TITLE
Unable to set LoadBalancerIp

### ISSUE THREAD

**Issue by sblaster** [emqx/emqx-rel#466]
#### Environment

- OS: K8S
- Erlang/OTP: 
- EMQ: 3.2.1
- Charts : 4.0.5

#### Description

I'm trying to deploy EMQX on a AKS K8S via Rancher. The idea is to use Azure LoadBalancer on a clustered EMQX. Everything is working great, except that the Public IP is renewed each deployement.

Indeed, in AKS, i have to add serivce.LoadBalancerIp to specify the Public IP already created in Azure. Is there a way to inject this param within the answer of the helm chart ?

 ```
 emqxConfig: 
    EMQX_CLUSTER__K8S__ADDRESS_TYPE: "Ip"
  service: 
    type: "LoadBalancer"
    loadBalancerIP: "104.*.*.*"

```
