### ISSUE TITLE
helm data persistence

### ISSUE THREAD

**Issue by An0nymous0** [emqx/emqx-rel#532]
Helm installation, use persistence.storageClass to persist data, changes on Dashboard are not cached in volume

Delete pods will be lost

![image](https://user-images.githubusercontent.com/6836030/85253096-02979400-b490-11ea-8994-029e9e8f5545.png)

**Comment by zhanghongtong** [comment]
Hi, @An0nymous0 apologies for the delay

Please provide more information about your k8s cluster

**Comment by An0nymous0** [comment]
1. values.yaml

```yaml
service:
    type: NodePort
replicaCount: 1 
persistence:
  enabled: true
  size: 1G
  storageClass: emqx
resources:
  limits:
    cpu: 1000m 
    memory: 1024Mi 
  requests:
    cpu: 100m 
    memory: 128Mi
emqxAclConfig: >
  #{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
  {allow, all, subscribe, ["$SYS/#"]}.
  {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
  {deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
  {allow, all}.
```

2. helm install emqx emqx/emqx -f values.yaml

3. kubectl delete  pods emqx-0

4. Data loss after pods restart automatically
