### ISSUE TITLE
Need to mount a secret with certificates

### ISSUE THREAD

**Issue by seguidor777** [emqx/emqx-rel#617]
Hello,

I am generating certificates with cert-manager using letsencrypt provider, there is a cert issuer that puts the files within a secret and I cannot read it from EMQ X. Can you please let me know how can I mount that secret?

**Comment by HJianBo** [comment]
No. This feature is not supported now.

We will try to support in the v4.2.4. Thanks for your reoport it :)

**Comment by seguidor777** [comment]
Thanks for letting me know.

For anyone else looking for this same feature, the workaround is to create a PVC and a job that copies the cert files from the secret to the claimed volume. I share you an example

emqx-pvc.yml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx
  namespace: commbat-cloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
  storageClassName: standard
```

emqx-mount-pvc.yml
```yaml
kind: Job
metadata:
  name: emqx-mount-pvc
spec:
  template:
    spec:
      containers:
      - args:
        - |
          adduser -DH emqx &&
          mkdir -p /mnt/etc/certs/emqx &&
          cp /etc/certs/emqx/* /mnt/etc/certs/emqx &&
          chown -R emqx:emqx /mnt/etc/certs/emqx
        command:
        - sh
        - -c
        image: busybox
        imagePullPolicy: Always
        name: copy-cert
        volumeMounts:
        - mountPath: /etc/certs/emqx
          name: emqx-cert
        - mountPath: /mnt
          name: emqx-pvc
      restartPolicy: Never
      volumes:
      - name: emqx-cert
        secret:
          defaultMode: 420
          secretName: emqx-cert
      - name: emqx-pvc
        persistentVolumeClaim:
          claimName: emqx-pvc
```
