### ISSUE TITLE
problem setting auth.jwt.verify_claims using environment variables

### ISSUE THREAD

**Issue by ravenblackdusk** [emqx/emqx-rel#637]
#### Environment

- OS: 5.10.7-3-MANJARO GNU/Linux
- Erlang/OTP: ?
- EMQ: ?

#### Description

this is the docker compose file i'm using:
```
  emqx:
    restart: unless-stopped
    logging:
      options:
        max-size: 1m
        max-file: "1"
    volumes:
      - ./jwt_public_key.pem:/etc/certs/jwt_public_key.pem
    image: emqx/emqx:latest
    environment:
      WAIT_FOR_ERLANG: 300
      EMQX_LOADED_PLUGINS: emqx_management,emqx_auth_jwt,emqx_recon,emqx_retainer,emqx_dashboard
      EMQX_AUTH__JWT__PUBKEY: /etc/certs/jwt_public_key.pem
      EMQX_AUTH__JWT__VERIFY_CLAIMS: "on"
      EMQX_auth__jwt__verify_claims__a: '%u' # for some reason only substrings of username work
      EMQX_auth__jwt__verify_claims__b: '%u' # for some reason only substrings of username work
      EMQX_auth__jwt__verify_claims__u: '%u' # for some reason only substrings of username work
      EMQX_auth__jwt__verify_claims__ua: '%u' # for some reason only substrings of username work
      EMQX_auth__jwt__verify_claims__ub: '%u' # for some reason only substrings of username work
      EMQX_auth__jwt__verify_claims__us: '%u' # for some reason only substrings of username work
      EMQX_auth__jwt__verify_claims__uu: '%u' # for some reason only substrings of username work
      EMQX_auth__jwt__verify_claims__camelCase: '%u' # this is what i need
      EMQX_ACL__NOMATCH: deny
      EMQX_ALLOW__ANONYMOUS: "false"
```
judging by docker logs only sub strings of username seem to work. I need to verify another claim.
