### ISSUE TITLE
Configuration broke in 4.3

### ISSUE THREAD

**Issue by perotom** [emqx/emqx-rel#651]
#### Environment

Docker image: emqx/emqx:4.3-rc.1

#### Description

We use the docker image with kubernetes. The following environment is used:

```
        env:
        - name: EMQX_LOADED_PLUGINS
          value: "emqx_management,emqx_auth_username,emqx_recon,emqx_retainer,emqx_dashboard"
        - name: EMQX_ALLOW_ANONYMOUS
          value: "false"
        - name: EMQX_MQTT__MAX_TOPIC_ALIAS
          value: "10"
        - name: EMQX_MQTT__MAX_PACKET_SIZE
          value: "32KB"
        - name: EMQX_MQTT__MAX_CLIENTID_LEN
          value: "128"
        - name: EMQX_AUTH__USER__PASSWORD_HASH
          value: "plain"
        - name: EMQX_AUTH__USER__1__USERNAME
          value: "helloworld"
        - name: EMQX_AUTH__USER__1__PASSWORD
          value: "test123"
        - name: EMQX_BROKER__SHARED_SUBSCRIPTION_STRATEGY
          value: "round_robin"
        - name: EMQX_BROKER__SHARED_DISPATCH_ACK_ENABLED
          value: "true"
        - name: EMQX_LOG__LEVEL
          value: "notice"
```
With docker image `emqx/emqx:4.2.9` it works flawless but when using `emqx/emqx:4.3-rc.1` or `emqx/emqx:latest` it doesn't. Seems like something with the configuration broke?
