### ISSUE TITLE
How to update emqx enterprise license without restart pod

### ISSUE THREAD

**Issue by xpunch** [emqx/emqx-rel#657]
I'm using emqx/emqx-ee@4.2.6 with helm, as the license will expire soon, I brought an new license.
After update emqxLicenseSecret in k8s, emqx.lic file didn't change in emqx pod.
Can I update license without redploy emqx cluster, cause this will make client disconnect.

**Comment by k32** [comment]
Hello,

Apologies in advance, since I don't know k8s very well, but from reading the definition of the emqx-ee helm chart, it looks like the chart mounts the secret configured as `emqxLicenseSecretName` as a volume in the container: 
```yaml
      volumes:
      {{- if .Values.emqxLicenseSecretName  }}
      - name: emqx-license
        secret:
          secretName: {{ .Values.emqxLicenseSecretName }}

...

      containers:
        - name: emqx
         ...
          volumeMounts:
          - ....
          {{ if .Values.emqxLicenseSecretName  }}
          - name: emqx-license
            mountPath: "/opt/emqx/etc/emqx.lic"
            subPath: "emqx.lic"
            readOnly: true
          {{ end }}
       ...
```

Perhaps the way forward is to edit the existing secret (`kubectl edit secrets <emqxLicenseSecretName>`) and wait until Kubernetes updates the mounted secret: https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically

But please keep in mind, that my experience in operating k8s is extremely limited, so maybe wait until someone else with more experience gives the answer.
