### ISSUE TITLE
Persistence  not work !!!

### ISSUE THREAD

**Issue by sxyandapp** [emqx/emqx-rel#661]
#### Environment

- OS: centos 7
- docker version:  19.03.5
- emqx docker image version: emqx/emqx:4.3.5

#### Description

When I try to persist, it report an error
my docker-compose:
```
    image: emqx/emqx:4.3.5
    environment:
      - EMQX_HOST=127.0.0.1
    ports:
      - 1883:1883
      - 18083:18083
    volumes:
      - /path/to/mqtt/data:/opt/emqx/data
      - /path/to/mqtt/log:/opt/emqx/log
      - /path/to/mqtt/etc:/opt/emqx/etc
```
error  message:
```
2021-07-20T07:49:35.951093+00:00 [error] Could not open file (/opt/emqx/etc/emqx.conf) for Reason enoent
```
